-- =====================================================
-- Schedule Master 테이블 생성 (Supabase)
-- SQL Editor에서 실행하세요
-- =====================================================

-- 1. sm_users 테이블
CREATE TABLE IF NOT EXISTS sm_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    pin TEXT,
    role TEXT DEFAULT 'member',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. sm_tasks 테이블
CREATE TABLE IF NOT EXISTS sm_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'todo',
    priority TEXT DEFAULT 'medium',
    due_date TEXT,
    task_date TEXT,
    task_time TEXT DEFAULT '09:00',
    duration INTEGER DEFAULT 60,
    category TEXT DEFAULT '업무',
    location TEXT,
    assignee_id BIGINT REFERENCES sm_users(id),
    created_by BIGINT REFERENCES sm_users(id),
    project_id TEXT,
    is_recurring INTEGER DEFAULT 0,
    recurring_type TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. sm_appointments 테이블
CREATE TABLE IF NOT EXISTS sm_appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    date TEXT NOT NULL,
    start_time TEXT,
    end_time TEXT,
    color TEXT DEFAULT '#b7131a',
    location TEXT,
    attendees TEXT,
    memo TEXT,
    created_by BIGINT REFERENCES sm_users(id),
    project_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. sm_comments 테이블
CREATE TABLE IF NOT EXISTS sm_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    user_id BIGINT REFERENCES sm_users(id),
    user_name TEXT,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. sm_invitations 테이블
CREATE TABLE IF NOT EXISTS sm_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by BIGINT REFERENCES sm_users(id),
    role TEXT DEFAULT 'member',
    token TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMP WITH TIME ZONE,
    used_by BIGINT REFERENCES sm_users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. sm_chip_presets 테이블
CREATE TABLE IF NOT EXISTS sm_chip_presets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    type TEXT DEFAULT 'title',
    usage_count INTEGER DEFAULT 0,
    is_system INTEGER DEFAULT 0,
    created_by BIGINT REFERENCES sm_users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_sm_tasks_project_id ON sm_tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_sm_tasks_status ON sm_tasks(status);
CREATE INDEX IF NOT EXISTS idx_sm_tasks_assignee ON sm_tasks(assignee_id);
CREATE INDEX IF NOT EXISTS idx_sm_comments_task ON sm_comments(task_id);
CREATE INDEX IF NOT EXISTS idx_sm_appointments_date ON sm_appointments(date);

-- 확인
SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';